version: "3.8"

services:
  app:
    build:
        context: ./
        dockerfile: ./builds/nodejs.Dockerfile
    restart: always
    ports:
      - "${APP}:3000"
    volumes: 
      - ./src/out:/usr/app
      - node_modules:/usr/data
    networks: 
      - rede

volumes: 
  node_modules:

networks: 
  rede: